server:
  port: 9998
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: bes-form-engine
          uri: lb://bes-form-engine
          predicates:
            - Path=/form/**
        - id: bes-form-assets
          uri: lb://bes-form-assets
          predicates:
            - Path=/assets/**
        - id: bes-form-build-in
          uri: lb://bes-form-engine-build-in
          predicates:
            - Path=/form-build-in/**
        - id: bes-iam-sso
          uri: lb://bes-iam-sso
          predicates:
            - Path=/iam/sso/**
        - id: bes-iam-management
          uri: lb://bes-iam-management
          predicates:
            - Path=/iam/management/**
        - id: platform-management
          uri: lb://platform-management
          predicates:
            - Path=/platform/management/**
        - id: platform-developer
          uri: lb://platform-developer
          predicates:
            - Path=/platform/developer/**
        - id: platform-model-engine
          uri: lb://platform-model-engine
          predicates:
            - Path=/platform/engine/model/**
        - id: platform-portal-engine
          uri: lb://platform-portal-engine
          predicates:
            - Path=/platform/engine/portal/**
        - id: casbin-demo
          uri: lb://casbin-demo #lb == loadbalance 负载均衡
          predicates:
            - Path=/casbin/**
        - id: platform-developer
          uri: lb://platform-developer
          predicates:
            - Path=/platform/developer/**
      # 全局熔断降级配置
#      default-filters:
#        - name: Hystrix
#          args:
#            name: default
#            #转发地址
#            fallbackUri: 'forward:/fallback'
#        - name: Retry
#          args:
#            #重试次数，默认值是 3 次
#            retries: 3
#            #HTTP 的状态返回码
#            statuses: BAD_GATEWAY,BAD_REQUEST
#            #指定哪些方法的请求需要进行重试逻辑，默认值是 GET 方法
#            methods: GET,POST
# hystrix 信号量隔离，3秒后自动超时
hystrix:
  enabled: true
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          semaphore:
            maxConcurrentRequests: 50
          strategy: SEMAPHORE
          thread:

nacos:
  config:
    #nacos地址
    server-addr: 192.168.0.81:8848
    #命名空间
    namespace: 33929324-9517-404e-90a6-556c0cb6741a
    #配置文件类型，目前只支持yaml,yml,properties,目前不需要了
    file-extension: yaml
    #默认提供者，目前不需要了
    refresh-enabled: true
    enabled: true
    group: BES

